### ISSUE TITLE
The Game doesn't end after a successful guess

### ISSUE THREAD

**Issue by 1nsaan** [KiranPolaki/GuessTheNumber#16]
The check and score are active even after a successful guess.
![image](https://github.com/KiranPolaki/GuessTheNumber/assets/110364595/9d992e05-7a01-42d1-91e4-87527b2998f3)
![image](https://github.com/KiranPolaki/GuessTheNumber/assets/110364595/ec30d72f-6ace-452e-96cc-1e48c096ea6a)

**Comment by KiranPolaki** [comment]
So u can disable the input feature once it is done!

**Comment by mohtasheem135** [comment]
please assign me this

**Comment by KiranPolaki** [comment]
@mohtasheem135 u can work on any other one, maybe i will create any thing that u can work on!
