### ISSUE TITLE
No favicon 

### ISSUE THREAD

**Issue by KiranPolaki** [KiranPolaki/GuessTheNumber#2]
Feel free to add a favicon for the webpage.

See below! make sure this issue is assigned to you before raising PR😀.

![image_2023-10-24_153729698](https://github.com/KiranPolaki/GuessTheNumber/assets/121670156/3bac1469-67bb-4a8e-86b0-78603e3cd9ca)

**Comment by Fahass** [comment]
Can I work on this issue?

**Comment by KiranPolaki** [comment]
Yes you can :)

**Comment by KiranPolaki** [comment]
Assigned! 

Add a suitable icon

if u are confused use this comment section to show me what you want to add! we will decide it together

Thank you
