### ISSUE TITLE
Creating Contributors page

### ISSUE THREAD

**Issue by NikhilKalloli** [KiranPolaki/GuessTheNumber#29]
Hey @KiranPolaki, can I use jQuery cross browser compatible way to handle common DOM tasks? If Yes then please assign this to me. I would like to contribute to this issue and please add the tags of hacktoberfest.

**Comment by KiranPolaki** [comment]
Great idea but that is too much work i guess?

**Comment by NikhilKalloli** [comment]
I would be just working with "script.js". I won't change any classes or whatsoever. So it will be fine. Can you please assign this to me? And please mention hacktoberfest tags.

**Comment by KiranPolaki** [comment]
I will be adding tags that's not an issue but i never worked with jquery so i am thinking🤣
. if any issue occurs then i will have to fix it right😅

**Comment by KiranPolaki** [comment]
But i still wanted to add a feature where there will be a button at the end of the game by clicking that we can see all the contributor's who contributed to this project🤔.
So if u are interested to do that i can assign that to you (or) i will do it myself anyways😅.

**Comment by NikhilKalloli** [comment]
> I will be adding tags that's not an issue but i never worked with jquery so i am thinking🤣 . if any issue occurs then i will have to fix it right😅

If that's the case I'll make a new branch and you can have two branches one with JQuery and other with Vanilla js. If you find it fine then you can merge them 😄

**Comment by NikhilKalloli** [comment]
> But i still wanted to add a feature where there will be a button at the end of the game by clicking that we can see all the contributor's who contributed to this project🤔. So if u are interested to do that i can assign that to you (or) i will do it myself anyways😅.

Yes please. I would like to work on that.

**Comment by KiranPolaki** [comment]
In the end i have to merge right😅. without that u can't get in hactoberfest

**Comment by KiranPolaki** [comment]
> > But i still wanted to add a feature where there will be a button at the end of the game by clicking that we can see all the contributor's who contributed to this project🤔. So if u are interested to do that i can assign that to you (or) i will do it myself anyways😅.
> 
> Yes please. I would like to work on that.

Sure😀

**Comment by NikhilKalloli** [comment]
> In the end i have to merge right😅. without that u can't get in hactoberfest. i am good with vanilla js but jQuery is not my thing.

Yep, I get it.

**Comment by NikhilKalloli** [comment]
> > > But i still wanted to add a feature where there will be a button at the end of the game by clicking that we can see all the contributor's who contributed to this project🤔. So if u are interested to do that i can assign that to you (or) i will do it myself anyways😅.
> > 
> > 
> > Yes please. I would like to work on that.
> 
> Sure😀
Thanks! I will start working on it. I need to render "newContributor.html" right?

**Comment by KiranPolaki** [comment]
i though of getting data from Git API's but i think that is too much to ask 😅
For now just apply the same styling as game to new contributor.html and update it and add a button in index.html where this will be redirected to newContributors.html

**Comment by NikhilKalloli** [comment]
I haven't worked with Git API😅. 
Okay Thanks, I'm working on it then👍

**Comment by NikhilKalloli** [comment]
Hey @KiranPolaki I've added "newContributor.html" with styling. Please merge it with tags. And if you need a favicon for "newContributor.html" I will start working on it once this PR gets merged. Have a nice a Day:)

**Comment by KiranPolaki** [comment]
FYI....
i just updated the contributors page😅 u can have a look if u want to know how we use git api's to fetch data and display them

**Comment by NikhilKalloli** [comment]
Hey @KiranPolaki that's amazing. It looks far more better than previous one. I was able to understand the code. I had been attending events so I didn't see your message.

**Comment by NikhilKalloli** [comment]
Btw, how long does it take to update me on that page? 😅. That looks cool.

**Comment by KiranPolaki** [comment]
Is it in waiting stage? probably they will take 7 days before confirming. in this 7 days ur merge request must not be canceled

Thank you

**Comment by NikhilKalloli** [comment]
Yes it is in waiting stage. Thanks for the clarification.

**Comment by KiranPolaki** [comment]
Don't focus on Hacktoberfest it is just the beginning. 

Focus on Learning and keep contributing😎

**Comment by NikhilKalloli** [comment]
Yeah sure. If you have any other projects then I would like to contribute there as well. Thanks!!
