### ISSUE TITLE
Bug fix

### ISSUE THREAD

**Issue by KiranPolaki** [KiranPolaki/GuessTheNumber#33]
Once the right answer is entered it must stay until we press again.

**Comment by NikhilKalloli** [comment]
Hey @KiranPolaki I can do this. Can you please assign it to me? And please add hackotoberfest tags.

**Comment by KiranPolaki** [comment]
Sure wok on it!

**Comment by NikhilKalloli** [comment]
I've created a pull request. Kindly review changes and merge it.

**Comment by KiranPolaki** [comment]
Sure!
