### ISSUE TITLE
The Score Value isnt reset to 20 after clicking "Again!" Button

### ISSUE THREAD

**Issue by JureBl** [KiranPolaki/GuessTheNumber#4]
Played it on https://kiranpolaki.github.io/GuessTheNumber/
if you play again the score value text is 20, but the value isnt reset properly.

**Comment by KiranPolaki** [comment]
Yes i see now🤔 it is reseting only the display value is that what you mean?

**Comment by JureBl** [comment]
Yes, its for hactoberfest2023. Should I make a new PR?

**Comment by KiranPolaki** [comment]
No its fine!
With changes u made is it working now u tested it in your local machine?

**Comment by JureBl** [comment]
Yes, I tested it on my local machine and it worked

**Comment by KiranPolaki** [comment]
Merged! and don't forgot to ⭐star the repo!
